### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by softexpert** [odddollar/Bilinear-gradient-generator-GUI#1]
Hello,

Nice tool and example of using Fyne !
Would it be possible to add a color picker ?
Being able to select the color at current cursor location will make an interesting feature, I think ...

**Comment by odddollar** [comment]
Oh that's a good idea. Like you click a pixel in the image and it gives you an RGBA code? I'll take a look at doing that.

Thanks for the suggestion!

**Comment by odddollar** [comment]
I've been working on this in the [picker](https://github.com/odddollar/Bilinear-gradient-generator-GUI/tree/picker) branch. You can click on a pixel in the image and it'll give you its value, but it's not quite finished as it currently just prints it out. I need to add a UI dialog for it next.
